universe            = vanilla
executable          = /afs/cern.ch/user/e/escheull/nobackup/hlt_nurd_con/condor_train_hlt_aggressive_critic.sh

output              = /afs/cern.ch/user/e/escheull/nobackup/hlt_nurd_con/condor_logs/train_hlt_aggressive_critic.out
error               = /afs/cern.ch/user/e/escheull/nobackup/hlt_nurd_con/condor_logs/train_hlt_aggressive_critic.err
log                 = /afs/cern.ch/user/e/escheull/nobackup/hlt_nurd_con/condor_logs/train_hlt_aggressive_critic.log

request_CPUs        = 4
request_memory      = 48GB
request_GPUs        = 1
+JobFlavour         = "tomorrow"

x509userproxy       = /afs/cern.ch/user/e/escheull/x509up
use_x509userproxy   = true

queue
