universe            = vanilla
executable          = /afs/cern.ch/user/e/escheull/nobackup/hlt_nurd_con/condor_train_ae.sh

output              = /afs/cern.ch/user/e/escheull/nobackup/hlt_nurd_con/condor_logs/train_ae.out
error               = /afs/cern.ch/user/e/escheull/nobackup/hlt_nurd_con/condor_logs/train_ae.err
log                 = /afs/cern.ch/user/e/escheull/nobackup/hlt_nurd_con/condor_logs/train_ae.log

request_CPUs        = 4
request_memory      = 48GB
request_GPUs        = 1
+JobFlavour         = "tomorrow"

queue
