universe            = vanilla
executable          = /afs/cern.ch/user/e/escheull/nobackup/hlt_nurd_con/condor_train_hlt_epoch_critic.sh

output              = /afs/cern.ch/user/e/escheull/nobackup/hlt_nurd_con/condor_logs/train_hlt_epoch_critic.out
error               = /afs/cern.ch/user/e/escheull/nobackup/hlt_nurd_con/condor_logs/train_hlt_epoch_critic.err
log                 = /afs/cern.ch/user/e/escheull/nobackup/hlt_nurd_con/condor_logs/train_hlt_epoch_critic.log

request_CPUs        = 4
request_memory      = 48GB
request_GPUs        = 1
+JobFlavour         = "tomorrow"

queue
